services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server"
    environment:
      DB_HOST: db
    volumes:
      - .:/var/www/sre-study
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0.40
    command:
      --default-authentication-plugin=mysql_native_password
      --collation-server=utf8mb4_general_ci
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
